let test_plugin = ref (fun () -> failwith "Should not be called."; ())
